"""cteate_user_model_with_new_fields

Revision ID: 341f06d09232
Revises: 3b6e7b1431b7
Create Date: 2025-12-19 23:21:44.082551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341f06d09232'
down_revision: Union[str, Sequence[str], None] = '3b6e7b1431b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.drop_column('users', 'name_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'department')
    op.drop_column('users', 'student_card')
    op.drop_column('users', 'group_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
