"""Initial tables

Revision ID: 3b6e7b1431b7
Revises: 
Create Date: 2025-12-17 20:49:13.463275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6e7b1431b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name_tmp', sa.String(), nullable=False),
    sa.Column('definition_tmp', sa.String(), nullable=True),
    sa.Column('latex_preambula_tmp', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_templates_template_id'), 'templates', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name_user', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('name_doc', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('latex_source', sa.Text(), nullable=True),
    sa.Column('creation_data_doc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changes_data_doc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=False)
    op.create_table('elements',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('name_elem', sa.String(), nullable=True),
    sa.Column('content_elem', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index(op.f('ix_elements_element_id'), 'elements', ['element_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('content_fb', sa.Text(), nullable=True),
    sa.Column('type_fb', sa.String(), nullable=True),
    sa.Column('creation_date_fb', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedbacks_feedback_id'), 'feedbacks', ['feedback_id'], unique=False)
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('name_img', sa.String(), nullable=True),
    sa.Column('url_img', sa.String(), nullable=True),
    sa.Column('heading_img', sa.String(), nullable=True),
    sa.Column('upload_data_img', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_images_image_id'), 'images', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_feedbacks_feedback_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_elements_element_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_template_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
